routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes(['register' => false]); 

Route::get('/', function () {
    return view('auth.login');
});

Route::get('/dashboard', 'DashboardController@index')->name('dashboard');
Route::get('/lang/change', 'LangController@change')->name('changeLang');

Route::resource('companies','CompanyController');
Route::resource('employees','EmployeeController');

	

app/Company.php
<?php
namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Company extends Model
{
    use SoftDeletes;

    protected $table = "companies";
    protected $fillable = [
        'name', 'email', 'logo', 'website'
    ];

    public function employee()
    {
        return $this->hasOne('App\Employee');
    }
}

app/Http/Controllers/CompanyController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests\CompanyRequest;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Storage;
use DB;
use Redirect;
use Auth;
use App\Company;
use App\Employee;
use App\Mail\SendEmail;
use App\Jobs\SendEmailJob;


class CompanyController extends Controller
{
    public function __construct()
    {
        $this->middleware('api');
    }

    public function index(Request $request)
    {      
        try 
        {
          if(count($request->all()) > 0) //check if there is request parameters
          {
              //request rows only
              if(isset($request->numrows) && !isset($request->by) && !isset($request->value))
              {
                  $companies = Company::latest()->paginate($request->numrows);           
              }
              //request filter dates    
              elseif($request->by == "created_at" || $request->by == "updated_at")
              {
                  $date = explode(",",str_replace(" - ",",",$request->datefilter));
                  $startDate = date('Y-m-d H:i:s', strtotime($date[0]));
                  $endDate = date('Y-m-d H:i:s', strtotime($date[1]));
                                  
                  $companies = Company::whereBetween('created_at',[$startDate,$endDate])
                               ->latest()->paginate($request->numrows); 
              }  
              //request by or value is null - set to default
              elseif(is_null($request->by) || is_null($request->value))
              {    
                  $request->numrows = 10; 
                  $companies = Company::latest()->paginate($request->numrows);
              }  
              //search by row, search by and value
              else
              {                
                  $companies = Company::where($request->by,'LIKE', "%{$request->value}%")
                                      ->latest()->paginate($request->numrows);                      
              }

            return view('companies.index',compact('companies','request'));
          }
          else
          {
             $companies = Company::latest()->paginate(10);
             return view('companies.index',compact('companies'));
          }        
        } 
          catch (\Throwable $th) 
        {
          return $th->getMessage();
           $errors = ['db' => 'Internal Server Error!'];
           return Redirect::back()->withErrors($errors); 
        }      
       
    }

    public function show(Company $company)
    {
        return view('companies.show',compact('company'));      
    }

    public function create()
    {
        return view('companies.create');
    }
    
    public function uploadImage($image,$imageName)
    {     
        if (!is_null($image))
        {
          Storage::put('public/'.$imageName, file_get_contents($image));
        }
    }

    public function store(CompanyRequest $request)
    {  
      try 
      {
        DB::beginTransaction();
        $image = null;
        $imageName = null;

          if($request->file('image'))
          {
            $image = $request->file('image'); 
            $imageName = Str::random(40).'.'. $image->extension();           
          }

          $request['logo'] = $imageName; 
          Company::create($request->all());
          $this->uploadImage($image,$imageName);  
          //*uncomment onQueue for future usage of multiple queues work with priority --queue=emails,default
          SendEmailJob::dispatch($request->except(['image']));//->onQueue('emails');      
          DB::commit();         

          return redirect()->route('companies.index')->with('success','Added Successfully'); 
      } 
      catch (\Throwable $th) 
      {
          DB::rollBack();
          $errors = ['db' => 'Internal Server Error!'];
          return Redirect::back()->withInput($request->all())->withErrors($errors);
      }      
    }
    
    public function edit(Company $company)
    {        
        return view('companies.edit',compact('company'));
    }

    public function update(CompanyRequest $request,Company $company)
    {
        try 
        {          
          DB::beginTransaction();
          $image = null;

          if($request->file('image'))
            {
              $image = $request->file('image'); 
              $imageName = Str::random(40).'.'. $image->extension();           
            }
          else $imageName = $request->logo; 
          $request->merge(['logo' => $imageName]);
          $company->update($request->all());
          $this->uploadImage($image,$imageName); 
          DB::commit();

          return redirect()->route('companies.index')->with('success','Updated Successfully');
        }
        catch (\Throwable $th)
        {
          DB::rollBack();
          $errors = ['db' => 'Internal Server Error!'];
          return Redirect::back()->withInput($request->all())->withErrors($errors);
        }
    }

    public function destroy(Company $company)
    {      
        try 
        {
            DB::beginTransaction();
            Employee::where('company_id',$company->id)->delete(); 
            $company->delete();   
            DB::commit(); 
            
            return redirect()->route('companies.index')->with('success','Deleted Successfully');
        } 
        catch (\Throwable $th) 
        {
            DB::rollBack();
            $errors = ['db' => 'Internal Server Error!'];
            return Redirect::back()->withErrors($errors); 
        }          
    }
}

resources/views/companies/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container-fluid">
<br>
<div class="d-flex justify-content-center">
            <!-- general form elements -->
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">{{ __('label.addNewCompany') }}</h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              <form method="POST" action="{{ route('companies.store')}}" enctype="multipart/form-data">
              @csrf
                <div class="card-body">
                
                  @if ($errors->any())
                    <div class="form-group alert alert-danger">
                      <ul>
                        @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                        @endforeach
                      </ul>
                    </div>                           
                  @endif

                  <div class="form-group">
                    <label for="InputName">{{ __('label.name') }}</label>
                    <input type="text" class="form-control" name="name" id="InputName" placeholder="{{ __('label.name') }}" value="{{ old('name') }}" maxlength="255"> 
                  </div>
                  <div class="form-group">
                    <label for="InputEmail">{{ __('label.email') }}</label>
                    <input type="text" class="form-control" name="email" id="InputEmail" placeholder="{{ __('label.email') }}" value="{{ old('email') }}" maxlength="255">
                  </div>
                  <div class="form-group">
                    <label for="InputLogo">{{ __('label.logo') }}</label>
                    <div class="input-group">
                      <div class="custom-file">
                        <input type="hidden" name="logo">
                        <input type="file" class="custom-file-input" name="image" id="InputLogo" accept="image/*">
                        <label class="custom-file-label" for="InputLogo">{{ __('label.chooseFile') }}</label>
                      </div>                    
                    </div>
                  </div>
                  <div class="form-group">
                    <label for="InputWebsite">{{ __('label.website') }}</label>
                    <input type="text" class="form-control" name="website" id="InputWebsite" placeholder="{{ __('label.website') }}" value="{{ old('website') }}" maxlength="255">
                  </div>
                </div>
                <!-- /.card-body -->

                <div class="card-footer">
                  <button type="submit" class="btn btn-primary">{{ __('label.submit') }}</button>
                </div>
              </form>
            </div>
</div>

  
</div>
@endsection

resources/views/companies/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container-fluid">
<br>
<div class="d-flex justify-content-center">
            <!-- general form elements -->
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">{{ __('label.editCompany') }}</h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              <form method="POST" action="{{ route('companies.update', $company->id)}}" enctype="multipart/form-data" onSubmit="return confirm('{{ __('label.confirmUpdate') }}');">
              @csrf
              @METHOD('PUT')
                <div class="card-body">

                @if ($errors->any())
                    <div class="form-group alert alert-danger">
                      <ul>
                        @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                        @endforeach
                      </ul>
                    </div>                           
                  @endif

                  <div class="form-group">
                    <label for="InputName">{{ __('label.name') }}</label>
                    <input type="text"  value="{{ old('name',  $company->name) }}" class="form-control" name="name" id="InputName" placeholder="Name" maxlength="255"> 
                  </div>
                  <div class="form-group">
                    <label for="InputEmail">{{ __('label.email') }}</label>
                    <input type="text" value="{{ old('email',  $company->email) }} " class="form-control" name="email" id="InputEmail" placeholder="Enter email" maxlength="255">
                  </div>
                  <div class="form-group">
                    <label for="InputEmail">{{ __('label.uploadedLogo') }}</label><br>
                    <image src="{{ asset('/storage/'.$company->logo)}}" height="100" width="100"/>
                  </div>
                  <div class="form-group">
                    <label for="InputLogo">{{ __('label.uploadNewLogo') }}</label>
                    <div class="input-group">
                      <div class="custom-file">
                        <input type="hidden" value="{{ $company->logo }}" name="logo">
                        <input type="file" class="custom-file-input" name="image" id="InputLogo" accept="image/*">
                        <label class="custom-file-label" for="InputLogo">{{ __('label.chooseFile') }}</label>
                      </div>                    
                    </div>
                  </div>
                  <div class="form-group">
                    <label for="InputWebsite">{{ __('label.website') }}</label>
                    <input type="text" value="{{ old('website', $company->website) }}" class="form-control" name="website" id="InputWebsite" placeholder="Website" maxlength="255">
                  </div>
                </div>
                <!-- /.card-body -->

                <div class="card-footer">
                  <button type="submit" class="btn btn-primary">{{ __('label.update') }}</button>
                </div>
              </form>
            </div>
</div>

  
</div>
@endsection

resources/views/companies/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container-fluid">
<br>
<h5 class="mb-2"> {{ __('label.companies') }}</h5>

  <div class="pull-right">
                <a class="btn btn-success" href="{{ route('companies.create') }}"> {{ __('label.createNewCompany') }}</a>
  </div>

  <br>
    <form method="GET">
      <div class="form-inline">
         <label>Number of Rows:</label>&nbsp;
         <input type="number" class="form-control col-md-1 changePagination" name="numrows" value="{{ isset($request->numrows) ? $request->numrows : 10 }}" >
      </div>      
      <div class="form-inline">
           <label>Search By:</label>&nbsp;
            <select class="form-control col-md-2" name="by" id="searchby">                         
                <option style="display: none;"></option>
                <option value="name" {{ isset($request->by) ? ($request->by == 'name' ? 'selected' : '') : '' }}>Name</option>
                <option value="email" {{ isset($request->by) ? ($request->by == 'email' ? 'selected' : '') : '' }}>Email</option>
                <option value="website" {{ isset($request->by) ? ($request->by == 'website' ? 'selected' : '') : '' }}>Website</option>
                <option value="created_at" {{ isset($request->by) ? ($request->by == 'created_at' ? 'selected' : '') : '' }}>Created</option>
                <option value="updated_at" {{ isset($request->by) ? ($request->by == 'updated_at' ? 'selected' : '') : '' }}>Updated</option>
            </select>

            &nbsp;
           <input type="text" name="datefilter" class="form-control col-md-4" id="reservationtime" value="{{ isset($request->datefilter) ? $request->datefilter : '' }}" style="display:none;">

            &nbsp;
           <input type="text" name="value" class="form-control col-md-3" id="searchValue" value="{{ isset($request->value) ? $request->value : '' }}"> 
           
            &nbsp;
          <input type="submit" value="Search" class="btn btn-block btn-info col-md-1">
      </div>
    </form>


                <table class="table table-bordered table-hover">
                  <thead>
                  <tr>
                    <th> {{ __('label.name') }}</th>
                    <th> {{ __('label.email') }}</th>
                    <th> {{ __('label.logo') }}</th>
                    <th> {{ __('label.website') }}</th> 
                    <th> {{ __('label.created_at') }}</th>     
                    <th> {{ __('label.updated_at') }}</th> 
                    <th> {{ __('label.action') }}</th>              
                  </tr>
                  </thead>
                  <tbody>
                  @if(is_null($companies))
                    </tbody>                  
                    </table>
                  @else
                    @foreach($companies as $company)
                    <tr>
                      <td>{{ $company->name }}</td>
                      <td>{{ $company->email }}</td>
                      <td><image src="{{ asset('/storage/'.$company->logo)}}" height="100" width="100"/></td>
                      <td>{{ $company->website }}</td>
                      <td>{{ date('d-M-Y h:i:s A', strtotime($company->created_at)) }}</td>
                      <td>{{ date('d-M-Y h:i:s A', strtotime($company->updated_at)) }}</td>
                      <td>  
                      <form action="{{ route('companies.destroy', $company->id) }}" method="POST" onSubmit="return confirm('{{ __('label.confirmCompanyDelete') }}');">
                          <a class="btn btn-info" href="{{ route('companies.show', $company->id) }}">  {{ __('label.show') }}</a>  
                          <a class="btn btn-primary" href="{{ route('companies.edit', $company->id) }}">  {{ __('label.edit') }}</a>
                        @csrf
                        @method('DELETE')
                        <button type="submit" class="btn btn-danger"> {{ __('label.delete') }}</button>
                      </form>
                      </td>
                    </tr> 
                    @endforeach   
                     
                  </tbody>                  
                </table>
                <div>
                
                Showing 
                 {{ ($companies->currentpage()-1) * $companies->perpage()+1}} to {{ $companies->currentpage() * $companies->perpage()}}
                   of  {{ $companies->total() }} entries
 
                </div>
                <div class="d-flex justify-content-center">
                    {!! $companies->appends(request()->query())->links() !!}            
                </div>
                @endif  
</div>
@endsection

resources/views/companies/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container-fluid">
<h5 class="mb-2 mt-4"></h5>

          <div class="col-md-6">
            <div class="card card-widget">
              <div class="card-header">
                  <span><h4>{{ $company->name }}</h4></span>
              </div>

              <div class="card-body">
                <span><h6>{{ __('label.email') }}: <b>{{ $company->email }}</b></h6></span>
                <span><h6>{{ __('label.website') }}:  <b>{{ $company->website }}</b></h6></span>
                <span><h6>{{ __('label.logo') }}:</h6></span>
                <img class="img-fluid pad" src="{{ asset('/storage/'.$company->logo)}}" alt="Photo">
                <br><br>
                <small>{{ __('label.created') }}: {{ $company->created_at }}</small>
                <br>
                <small>{{ __('label.lastUpdated') }}: {{ $company->updated_at }}</small>
              </div>
            </div>
          </div>
</div>
@endsection