routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes(['register' => false]); 

Route::get('/', function () {
    return view('auth.login');
});

Route::get('/dashboard', 'DashboardController@index')->name('dashboard');
Route::get('/lang/change', 'LangController@change')->name('changeLang');

Route::resource('companies','CompanyController');
Route::resource('employees','EmployeeController');

	

app/Employee.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Employee extends Model
{
    use SoftDeletes;
    protected $table = "employees";
    protected $fillable = [
        'first_name', 'last_name', 'company_id', 'email', 'phone'
    ];

    public function company()
    {
        return $this->belongsTo('App\Company', 'company_id')->withTrashed();
    }
}

app/Http/Controllers/EmployeeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Database\Eloquent\ModelNotFoundException;
use App\Http\Requests\EmployeeRequest;
use Illuminate\Database\Eloquent\Builder;
use DB;
use App\Employee, App\Company;
use Redirect;


class EmployeeController extends Controller
{
    public function __construct()
    {
        $this->middleware('api');
    }
    
    public function index(Request $request)
    {
        try 
        {
            if (count($request->all()) > 0) 
            {
                //request rows only
                if(isset($request->numrows) && !isset($request->by) && !isset($request->value))
                {
                        $employees = Employee::with('company')->latest()->paginate($request->numrows);            
                }
                //request filter dates    
                elseif($request->by == "created_at" || $request->by == "updated_at")
                {
                    $date = explode(",",str_replace(" - ",",",$request->datefilter));
                    $startDate = date('Y-m-d H:i:s', strtotime($date[0]));
                    $endDate = date('Y-m-d H:i:s', strtotime($date[1]));
                                    
                    $employees = Employee::whereBetween('created_at',[$startDate,$endDate])
                                ->latest()->paginate($request->numrows); 
                }  
                //request by or value is null - set to default
                elseif(is_null($request->by) || is_null($request->value))
                {    
                        $request->numrows = 10; 
                        $employees = Employee::with('company')->latest()->paginate($request->numrows);        
                }  
                //search by row, search by and value
                else
                {
                    if($request->by === "company")
                    {
                        $employees = Employee::with('company')->whereHas('company', function (Builder $q) use ($request) {
                              $q->where('name', 'LIKE', "%{$request->value}%");
                         })->latest()->paginate($request->numrows);
                    }
                    else
                    {
                        $employees = Employee::with('company')
                                            ->where($request->by, 'LIKE', "%{$request->value}%")
                                            ->latest()->paginate($request->numrows);
                    }                               
                }   

                return view('employees.index',compact('employees','request'));        
            }
            else
            {
                $employees = Employee ::with('company')->latest()->paginate(10);  
                return view('employees.index',compact('employees'));
            }         
        } 
          catch (\Throwable $th) 
        {
           $errors = ['db' => 'Internal Server Error!'];
           return Redirect::back()->withErrors($errors); 
        }           
    }

    public function show(Employee $employee)
    {
        return view('employees.show',compact('employee'));
    }

    public function create()
    {
        try 
        {
            $companies = Company::all('id','name');
            return view('employees.create',compact('companies'));
        } 
        catch (\Throwable $th) 
        {
           $errors = ['db' => 'Internal Server Error!'];
           return Redirect::back()->withErrors($errors); 
        }
       
    }
 
    public function store(EmployeeRequest $request)
    {
            try 
            {
                DB::beginTransaction();
                Employee::create($request->all());         
                DB::commit();
                return redirect()->route('employees.index')->with('success','Added Successfully');                     
            } 
            catch (\Throwable $th) 
            {
                DB::rollBack();
                $errors = ['db' => 'Internal Server Error!'];
                return Redirect::back()->withInput($request->all())->withErrors($errors);
            }
    }

    public function edit(Employee $employee)
    {
        try 
        {
            $companies = Company::all('id','name');
            return view('employees.edit',compact('employee','companies'));
        } 
        catch (\Throwable $th) 
        {
            $errors = ['db' => 'Internal Server Error!'];
            return Redirect::back()->withErrors($errors); 
        }
      
    }

    public function update(EmployeeRequest $request, Employee $employee)
    {
            try 
            {
                DB::beginTransaction();
                $employee->update($request->all());    
                DB::commit();
                return redirect()->route('employees.index')->with('success','Updated Successfully');                                    
            } 
            catch (\Throwable $th) 
            {
                DB::rollBack();
                $errors = ['db' => 'Internal Server Error!'];
                return Redirect::back()->withInput($request->all())->withErrors($errors);
            }        
    }

    public function destroy(Employee $employee)
    {                     
            try 
            {
                DB::beginTransaction();
                $employee->delete();    
                DB::commit();
                
                return redirect()->route('employees.index')->with('success','Deleted Successfully');                         
            } 
            catch (\Throwable $th) 
            {
               DB::rollBack();
               $errors = ['db' => 'Internal Server Error!'];
               return Redirect::back()->withErrors($errors); 
            }                                                                                                                                   
    }
}

resources/views/employees/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container-fluid">
<br>             

<div class="d-flex justify-content-center">
            <!-- general form elements -->
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">{{ __('label.addNewEmployee') }}</h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              <form method="POST" action="{{ route('employees.store')}}">
              @csrf
              
                <div class="card-body">
                  @if ($errors->any())
                    <div class="form-group alert alert-danger">
                      <ul>
                        @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                        @endforeach
                      </ul>
                    </div>                           
                  @endif

                  <div class="form-group">
                    <label for="InputFirstName">{{ __('label.firstName') }}</label>
                    <input type="text" class="form-control" name="first_name" id="InputFirstName" placeholder="{{ __('label.firstName') }}" value="{{ old('first_name') }}" maxlength="255"> 
                  </div>
                  <div class="form-group">
                    <label for="InputLastName">{{ __('label.lastName') }}</label>
                    <input type="text" class="form-control" name="last_name" id="InputLastName" placeholder="{{ __('label.lastName') }}" value="{{ old('last_name') }}" maxlength="255"> 
                  </div>
                  <div class="form-group">
                    <label for="InputCompany">{{ __('label.company') }}</label>
                      <select name="company_id" class="form-control" id="SelectCompany" required>
                        <option style="display:none"></option>
                        @foreach($companies as $company)
                        <option value="{{ $company->id }}" {{ (old('company_id') == $company->id ? "selected":"") }}>{{ $company->name }}</option>
                        @endforeach
                      </select>
                  </div>
                  <div class="form-group">
                    <label for="InputEmail">{{ __('label.email') }}</label>
                    <input type="text" class="form-control" name="email" id="InputEmail" placeholder="{{ __('label.email') }}" value="{{ old('email') }}" maxlength="255">
                  </div>
                  <div class="form-group">
                    <label for="InputPhone">{{ __('label.contactNo') }}</label>
                    <input type="text" class="form-control" name="phone" id="InputPhone" placeholder="Phone"  value="{{ old('phone') }}" maxlength="255">
                  </div>
                </div>
                <!-- /.card-body -->

                <div class="card-footer">
                  <button type="submit" class="btn btn-primary">{{ __('label.submit') }}</button>
                </div>
              </form>
            </div>

  


</div>
</div>
@endsection

resources/views/employees/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container-fluid">
<br>
<div class="d-flex justify-content-center">
            <!-- general form elements -->
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">{{ __('label.editEmployee') }}</h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              <form method="POST" action="{{ route('employees.update',$employee->id) }}" onSubmit="return confirm('{{ __('label.confirmUpdate') }}');">
              @csrf
              @METHOD('PUT')
                <div class="card-body">

                  @if ($errors->any())
                    <div class="form-group alert alert-danger">
                      <ul>
                        @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                        @endforeach
                      </ul>
                    </div>                           
                  @endif
                  <input type="hidden" value="{{ old('id',  $employee->id) }}"class="form-control" name="id"> 
                  <div class="form-group">
                    <label for="InputFirstName">{{ __('label.firstName') }}</label>
                    <input type="text" value="{{ old('first_name',  $employee->first_name) }}"class="form-control" name="first_name" id="InputFirstName" placeholder="{{ __('label.firstName') }}" maxlength="255"> 
                  </div>
                  <div class="form-group">
                    <label for="InputLastName">{{ __('label.lastName') }}</label>
                    <input type="text" value="{{ old('last_name',  $employee->last_name) }}" class="form-control" name="last_name" id="InputLastName" placeholder="{{ __('label.lastName') }}" maxlength="255"> 
                  </div>
                  <div class="form-group">
                    <label for="InputCompany">{{ __('label.company') }}</label>
                      <select name="company_id" class="form-control" id="SelectCompany" required>
                        <option style="display:none"></option>
                        @foreach($companies as $company)
                        <option value="{{ $company->id }}" {{  $company->id == old('company_id', $employee->company->id) ? 'selected' : ''}}>{{ $company->name }}</option>
                        @endforeach
                      </select>
                  </div>
                  <div class="form-group">
                    <label for="InputEmail">{{ __('label.email') }}</label>
                    <input type="text" value="{{ old('email', $employee->email) }}" class="form-control" name="email" id="InputEmail" placeholder="{{ __('label.email') }}" maxlength="255">
                  </div>
                  <div class="form-group">
                    <label for="InputPhone">{{ __('label.contactNo') }}</label>
                    <input type="text" value="{{ old('phone', $employee->phone) }}" class="form-control" name="phone" id="InputPhone" placeholder="Phone" maxlength="255">
                  </div>
                </div>
                <!-- /.card-body -->

                <div class="card-footer">
                  <button type="submit" class="btn btn-primary">{{ __('label.update') }}</button>
                </div>
              </form>
            </div>
</div>
</div>
@endsection

resources/views/employees/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container-fluid">
<br>
<h5 class="mb-2">{{ __('label.employees') }}</h5>

  <div class="pull-right">
                  <a class="btn btn-success" href="{{ route('employees.create') }}"> Create New Employee</a>
  </div>

  <br>

    <form method="GET">
      <div class="form-inline">
        <label>Number of Rows:</label>&nbsp;
        <input type="number" class="form-control col-md-1 changePagination" name="numrows" value="{{ isset($request->numrows) ? $request->numrows : 10 }}" >
      </div>  
      
      <div class="form-inline">
           <label>Search By:</label>&nbsp;
           <select class="form-control col-md-2" name="by" id="searchby">         
                <option style="display:none"></option>  
                <option value="first_name" {{ isset($request->by) ? ($request->by == 'first_name' ? 'selected' : '') : '' }} >First Name</option>
                <option value="last_name" {{ isset($request->by) ? ($request->by == 'last_name' ? 'selected' : '') : '' }} >Last Name</option>
                <option value="company" {{ isset($request->by) ? ($request->by == 'company' ? 'selected' : '') : '' }} >Company</option>
                <option value="email" {{ isset($request->by) ? ($request->by == 'email' ? 'selected' : '') : '' }} >Email</option>
                <option value="phone" {{ isset($request->by) ? ($request->by == 'phone' ? 'selected' : '') : '' }} >Contact No.</option>
                <option value="created_at" {{ isset($request->by) ? ($request->by == 'created_at' ? 'selected' : '') : '' }} >Created</option>
                <option value="updated_at" {{ isset($request->by) ? ($request->by == 'updated_at' ? 'selected' : '') : '' }} >Updated</option>
            </select>
            &nbsp;

            &nbsp;
           <input type="text" name="datefilter" class="form-control col-md-4" id="reservationtime" value="{{ isset($request->datefilter) ? $request->datefilter : '' }}" style="display:none;">

            &nbsp;
           <input type="text" name="value" class="form-control col-md-3" id="searchValue" value="{{ isset($request->value) ? $request->value : '' }}"> 
           
            &nbsp;
           <input type="submit" value="Search" class="btn btn-block btn-info col-md-1">
      </div>
    </form>


                <table class="table table-bordered table-hover">
                  <thead>
                  <tr>
                    <th>{{ __('label.firstName') }}</th>
                    <th>{{ __('label.lastName') }}</th>
                    <th>{{ __('label.company') }}</th>
                    <th>{{ __('label.email') }}</th> 
                    <th>{{ __('label.contactNo') }}</th>   
                    <th>{{ __('label.created_at') }}</th> 
                    <th>{{ __('label.updated_at') }}</th>    
                    <th>{{ __('label.action') }}</th>            
                  </tr>
                  </thead>
                  <tbody>
                  @if(is_null($employees))
                    </tbody>                  
                    </table>
                  @else
                    @foreach($employees as $employee)
                    <tr>
                      <td>{{ $employee->first_name }}</td>
                      <td>{{ $employee->last_name }}</td>
                      <td>{{ $employee->company->name }}</td>
                      <td>{{ $employee->email }}</td>
                      <td>{{ $employee->phone }}</td>
                      <td>{{ date('d-M-Y h:i:s A', strtotime($employee->created_at)) }}</td>
                      <td>{{ date('d-M-Y h:i:s A', strtotime($employee->updated_at)) }}</td>
                      <td>  
                      <form action="{{ route('employees.destroy', $employee->id) }}" method="POST" onSubmit="return confirm('{{ __('label.confirmDelete') }}');">
                          <a class="btn btn-info" href="{{ route('employees.show', $employee->id) }}"> {{ __('label.show') }}</a>  
                          <a class="btn btn-primary" href="{{ route('employees.edit', $employee->id) }}"> {{ __('label.edit') }}</a>
                        @csrf
                        @method('DELETE')
                        <button type="submit" class="btn btn-danger">{{ __('label.delete') }}</button>
                      </form>
                      </td>
                    </tr> 
                    @endforeach              
                  </tbody>                  
                </table>
                <div>Showing 
                 {{ ($employees->currentpage()-1) * $employees->perpage()+1}} to {{ $employees->currentpage() * $employees->perpage()}}
                   of  {{ $employees->total() }} entries
                </div>
                <div class="d-flex justify-content-center">
                  {!! $employees->appends(request()->query())->links() !!}    
                </div>
              @endif  
  
</div>
@endsection

resources/views/employees/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container-fluid">
<h5 class="mb-2 mt-4"></h5>

          <div class="col-md-6">
            <div class="card card-widget">
              <div class="card-header">
                  <span><h4>{{ $employee->first_name . ' ' . $employee->last_name }}</h4></span>
              </div>

              <div class="card-body">
                <span><h6>{{ __('label.company') }}: <b>{{ $employee->company->name }}</b></h6></span>
                <span><h6>{{ __('label.email') }}: <b>{{ $employee->email }}</b></h6></span>
                <span><h6>{{ __('label.contactNo') }}:  <b>{{ $employee->phone }}</b></h6></span>                
                <br>
                <small>{{ __('label.created') }}: {{ $employee->created_at }}</small>
                <br>
                <small>{{ __('label.lastUpdated') }}: {{ $employee->updated_at }}</small>
              </div>
            </div>
          </div>
</div>
@endsection